# Generated by Django 5.0.1 on 2024-01-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shop_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='category',
        ),
        migrations.AddField(
            model_name='shop',
            name='categories',
            field=models.ManyToManyField(to='core.category'),
        ),
    ]
